#!/bin/bash

if [ -z "$1" ]; then
	dev="/dev/hidraw0"
else
	dev="$1"
fi

g++ WrapReader.cpp -lrt -o WrapReader && if [ ! -r $dev ]; then sudo chmod +r $dev; fi && ./WrapReader $dev | python -u Graph.py -txt -png > graphs/`date +%s`.txt
